baseURL = "/"
languageCode = "en-us"
title = "stochasmos"

[permalinks]
  blog = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "categories"
    pre = "categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "tags"
    pre = "tag"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    name = "series"
    pre = "series"  
    url = "/series/"
    weight = 5
  # [[menu.main]]
  #   name = "reading list"
  #   pre = "books"
  #   url = "/books/"
  #   weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "You just made a Hugo blog from scratch."

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"